[versions]
agp = "8.9.0"
androidxJunit = "1.1.3"
appcompatVersion = "1.3.0"
canopenAndroid = "1.0.0"
constraintlayout = "2.2.0"
coreKtx = "1.15.0"
espressoCoreVersion = "3.4.0"
gson = "2.10.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
kotlinStdlib = "2.0.0"
recyclerview = "1.4.0"

[libraries]
appcompat-v130 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
canopen-android = { module = "com.github.mik3y:canopen-android", version.ref = "canopenAndroid" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
espresso-core-v340 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
junit-v113 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinStdlib" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

